### ISSUE TITLE
Allow settings the formats in pixels

### ISSUE THREAD

**Issue by paladox** [kmoskwiak/videojs-resolution-switcher#1]
Hi please add support for settings formats in pixel wise since hd and sd and 4k but other formats not really have a name so please allow users to customise it.

**Comment by kmoskwiak** [comment]
Do you mean something like this: 
```
player.updateSrc([
  { type: "video/mp4", src: "http://www.example.com/path/to/video.mp4", label: '144' },
  { type: "video/mp4", src: "http://www.example.com/path/to/video.mp4", label: '360' }
])
```
you can use pixels for label. Those values will be treated as string and displayed in menu.

**Comment by paladox** [comment]
Ok.
