### ISSUE TITLE
Can sync this plugin for latest videojs version 7.3.0 or 7+

### ISSUE THREAD

**Issue by ahmadshc** [kmoskwiak/videojs-resolution-switcher#125]
hello and thank you for great plugin for videojs
but only work correct with videojs 5+ versions and not work 7+
can sync this plugin for latest videojs version 7.3.0 or 7+
i hope see this feature
thank you very much

**Comment by beznosd** [comment]
This solution works well for 7.3.0 too
https://github.com/kmoskwiak/videojs-resolution-switcher/issues/88#issuecomment-311984273

**Comment by ahmadshc** [comment]
> This solution works well for 7.3.0 too
> #88

Thank you
