### ISSUE TITLE
Require video.js, not videojs

### ISSUE THREAD

**Issue by ropez** [kmoskwiak/videojs-resolution-switcher#14]
The NPM package for video.js is called [video.js](https://www.npmjs.com/package/video.js)

When using webpack, the module fails to load.

**Comment by kprimdal** [comment]
Also breaks Gulp, change line `11-15` to:

    if(typeof window.videojs === 'undefined' && typeof require === 'function') {
        videojs = require('video.js');
     } else {
        videojs = window.videojs;
     }

**Comment by kmoskwiak** [comment]
fixed in 0.2.2. thanks

**Comment by ropez** [comment]
ty
