### ISSUE TITLE
Filter on sources supported by tech

### ISSUE THREAD

**Issue by hartman** [kmoskwiak/videojs-resolution-switcher#15]
It would be really nice to filter the results of the dropdown based on them being supported by the current technology.

**Comment by hartman** [comment]
This depends on https://github.com/videojs/video.js/issues/2705

**Comment by paladox** [comment]
This https://github.com/videojs/video.js/issues/2705 has been closed as https://github.com/videojs/video.js/issues/2705#issuecomment-171890864 it has partly been done.
