### ISSUE TITLE
Not an issue; YouTube feature support?

### ISSUE THREAD

**Issue by alijaffar** [kmoskwiak/videojs-resolution-switcher#17]
Hey, great plugin. I'm trying to make it work with videojs-youtube but to no avail. Would you care to add support for it? Right now -- I plan to make the toggle reload with new YouTube options, it should work. I'll post when I have something.

**Comment by kmoskwiak** [comment]
Thanks :) My first attempts are in 'feature-youtube' branch. It's not finished yet, but it does switch quality.

**Comment by kmoskwiak** [comment]
v0.4.0 now supports youtube tech
