### ISSUE TITLE
Switching src during playback fails to resume if preload == none

### ISSUE THREAD

**Issue by hartman** [kmoskwiak/videojs-resolution-switcher#19]
When a video element has preload set to none, and we switch the during playback, then we will have to manually .load(), because otherwise the loadeddata event will never trigger and we will therefore not resume playback.

This is explained by https://github.com/videojs/video.js/blob/master/src/js/player.js#L1845

**Comment by kmoskwiak** [comment]
Fixed in 0.2.3 with  #20
