### ISSUE TITLE
Dosent work 

### ISSUE THREAD

**Issue by paladox** [kmoskwiak/videojs-resolution-switcher#2]
It dosent register properly because videoJsResolutionSwitcher is not a function it is videoJsResolutionSwitcher = function(option)

it should be function videoJsResolutionSwitcher(option) but that makes the error go away a new one comes up so please test a fix you propose to use please.

**Comment by kmoskwiak** [comment]
What version of video.js you are using?

**Comment by paladox** [comment]
5.0 rc 90

**Comment by kmoskwiak** [comment]
I've updated plugin to video.js 5.0.0-rc.90. The only issue I've found was in css (menu items were misplaced).

I couldn't reproduce the error you're writing about. Could you please add more details? Or an example?

The plugin register itself here ([L159](https://github.com/kmoskwiak/videojs-resolution-switcher/blob/master/lib/videojs-resolution-switcher.js#L159))
```
videojs.plugin('videoJsResolutionSwitcher', videoJsResolutionSwitcher);
```
`videojs.plugin` takes 2 arguments. First (string) is the name of plugin, second is a function.
`videojs.plugin` adds to player new method `videoJsResolutionSwitcher` as prototype ([here](https://github.com/videojs/video.js/blob/v5.0.0-rc.72/src/js/plugins.js#L13-L15))

```
var videoJsResolutionSwitcher;
videoJsResolutionSwitcher = function(option){}
```
The code above defines function via function expression. So in `videojs.plugin('videoJsResolutionSwitcher', videoJsResolutionSwitcher);` I pass the function as expected.
