### ISSUE TITLE
Dispose function not available for resolutionSwitcher

### ISSUE THREAD

**Issue by Sebi55** [kmoskwiak/videojs-resolution-switcher#25]
Hey,

I have got the problem that I want to use the updateSrc function to dynamically change the videos source specific to the page you visit but I always get this error:
player.controlBar.resolutionSwitcher.dispose is not a function

And it is really that simple that the resolutionSwitcher Object does not have the dispose function attached and also the control bar of videojs otherwise I would have just disposed this.
I am using the newest stable version of videojs which is 5.4.6.

I am initializing the player like this:
```javascript
var video_player=videojs( '#video_player', { controls: true, "autoplay": true,width:"650",
    plugins: {
        videoJsResolutionSwitcher: {
          default: 'high',
          dynamicLabel: true
        }
      },"preload": "auto" });
```
I visit my first video and it works perfectly and loads the video. When going to another video now the player should dynamically load the new video but now the dispose function would be run to remove the old selectors but like already said the dispose function is not found.
What am I doing wrong?

**Comment by mildrenben** [comment]
@Sebi55 I'm having the same issue and cannot find a solution. Did you figure it out?

**Comment by Sebi55** [comment]
No not yet didn't have the time to investigate. I tried to update to the newest version of videojs today just to see if that fixes the problem but apparently not. Which version are you using?
Do you have an idea yet?

**Comment by mildrenben** [comment]
@Sebi55 For some reason this plugin doesn't have the dispose method. I ended up just removing the elem from the DOM using jQuery and all was fixed (note you have to use jQuery, not native .removeChild method). On line 159 do the following: 

```
if(player.controlBar.resolutionSwitcher){
                    $('.vjs-resolution-button').remove(); // ------Add this part in
                    //player.controlBar.resolutionSwitcher.dispose(); ----- Comment this part out
                    delete player.controlBar.resolutionSwitcher;
                }
```

**Comment by Sebi55** [comment]
@mildrenben That works perfectly. And you are right it doesn't implement the dispose method.
He should add a fix because this is not the nicest way to fix this.
