### ISSUE TITLE
Can the default resolution be chosen automatically based on the user bandwidth?

### ISSUE THREAD

**Issue by raymanound** [kmoskwiak/videojs-resolution-switcher#26]
Lately, I try videojs to setup video in my website.

It is great and easy to setting up different resolution videos by this plugin.

However, I want the default resolution can be selected dynamically based on the user bandwidth like Youtube or Vimeo videos. I do not know where to start and could anyone give some advices to help me out?

**Comment by kmoskwiak** [comment]
currently no. 

You can do it like this:
1. somehow check user bandwidth
2. let's say that best video has index 2 in array of sources
3. initialize player:

```
videojs('video', {
      plugins: {
        videoJsResolutionSwitcher: {
          default: 2 // index of video
        }
      }
    }, function(){
      // this is player
    })
```
