### ISSUE TITLE
Player freezes on source switch

### ISSUE THREAD

**Issue by Fenrirthviti** [kmoskwiak/videojs-resolution-switcher#34]
When switching sources, the player "freezes" temporarily. The entire player frame goes black, and is unresponsive until it is clicked on, at which point the proper playback resumes. This behavior is able to be replicated on the live demo page, as well as my own webserver when using the multiple source tag method. I am not sure what additional information will help with this bug, but please let me know and I will provide whatever you need. Thanks!

**Comment by kmoskwiak** [comment]
Not sure if it's a bug. Switching qualities in this plugin is simply changing video source. Since it is only mp4 file (or other) it cant be smooth. I guess using hls or dash would make switching smooth. Currently this plugin does not support these techs, but I will add it soon.

**Comment by mishazawa** [comment]
I have this problem. After switching source, player need to be triggered by mouse click, to continue playing with new source.
