### ISSUE TITLE
VIDEOJS: WARN: player.hls is deprecated. Use player.tech.hls instead.

### ISSUE THREAD

**Issue by SensicalCat** [kmoskwiak/videojs-resolution-switcher#37]
Using Video.js v.5.6.0 
videojs-contrib-hls - v1.3.7
videojs-resolution-switcher - 2015-7-26

This warning appears in the console.

**Comment by kmoskwiak** [comment]
I guess you have to use player.tech_.hls instead player.hls

this issue should be posted in videojs-contrib-hls anyway
