### ISSUE TITLE
Resolution YouTube no change

### ISSUE THREAD

**Issue by Askancy** [kmoskwiak/videojs-resolution-switcher#42]
Hello I tried to change the YouTube video resolution but does not seem to work, even in the sample site...

If I try to put the resolution 144 and 720p there are no changes.. I tried both with Chrome that with Edge

**Comment by kmoskwiak** [comment]
It does not work immediately (it does not force the quality). I guess it's a feature of YouTube API (?), which makes switching qualities smooth. 

Quality changes immediately after seeking.

Try this: Play video. Change quality to the worst (144) and change position of video in seek bar (try the moment where video is not loaded yet). You should notice quality change. Then change quality to the best (1080) and wait. You should notice that progress bar cleaned itself and it is loading video again. After few seconds you should notice change. Check console (in the sample site) if there is info: `Source changed`

Is that your case? I will investigate if there are other possibilities of changing quality in YT tech (more aggressive perhaps).

**Comment by Askancy** [comment]
It would be great change forced resolution, unfortunately I tried as you told me, but the resolution still does not change...

**Comment by alijaffar** [comment]
I had the same concern as @Askancy, but it works just the same for users as you described @kmoskwiak . Forcing resolution change would be nice, though... perhaps a) dispose the player and re-initialize, or b) implement it through a source change.

I would consider this closed, see this [post for more info](http://android.stackexchange.com/questions/103239/youtube-resumes-playing-video-on-old-quality-even-after-i-change-the-quality-set).
