### ISSUE TITLE
Support downloading videos

### ISSUE THREAD

**Issue by paladox** [kmoskwiak/videojs-resolution-switcher#43]
Hi please add the support for downloading videos through this plugin please.

YouTube I doint think we can support it for that but downloading from our own websites or other websites that allow downloading.

**Comment by alijaffar** [comment]
This is totally out of scope; this plugin is for changing resolution. 
Also, downloading YouTube videos is against their Terms of Service, so their API's do not support that.

**Comment by paladox** [comment]
@alijaffar hi if you read the note at the bottom I said probably doint support youtube. But I'm talking about downloading our local videos from our website.

**Comment by mkody** [comment]
@paladox This is still out of scope here.
If it's your website, just add a download link below your player?
```html
<a download href="/path/to/video.mp4">Download link</a>
```

**Comment by kmoskwiak** [comment]
I agree with @mkody 

This is out od scope. You could add link to download file as in mkody's example. If you want download currently selected resolution you can use `player.currentResolution()` method
