### ISSUE TITLE
Cannot play in rtmp streaming video

### ISSUE THREAD

**Issue by suarezph** [kmoskwiak/videojs-resolution-switcher#66]
Hi does this plugin works in rtmp live video streaming?

**Comment by suarezph** [comment]
i have close the issue as the RTMP live streaming is working.

**Comment by professorhaseeb** [comment]
@aaesis I have the same issue. how did you solved it?

**Comment by suarezph** [comment]
@professorhaseeb its been 2 years, I can't remember how I solve it but can you expound more into this.
