### ISSUE TITLE
Add API to get current resolution

### ISSUE THREAD

**Issue by philipgiuliani** [kmoskwiak/videojs-resolution-switcher#7]
Adding the following function would be nice: `getCurrentResolution()`

Another possibility would be to add the current resolution to the player element (data-current-res) or to pass the selected resolution into the `resolutionchange` event.

**Usecase**
I would like to store the last resolution of the user (via the `resolutionchange` event) in a cookie.

**Comment by kmoskwiak** [comment]
It's very good idea. I think I add memorization of resolution in localStorage or cookie.

As for `getCurrentResolution()` method - I am wondering what should it return. It could return just label name (String) e.g. `sd` or `360p` - it reflects user's choice. I could also pass sources array:
```
[{
 label: 'sd',
 src: 'src1.mp4',
 res: 360,
 type: 'video/mp4'
},{
 label: 'sd',
 src: 'src1.webm',
 res: 360,
 type: 'video/webm'
}]
```
Array contains all sources with label `sd` regardless of type. Any suggestions? Am I overthinking it? :P

**Comment by kmoskwiak** [comment]
I've added `currentResolution()` method which acts as getter or setter.

**Comment by philipgiuliani** [comment]
Great thank you!! :)
