### ISSUE TITLE
Gear icon not showing at all 

### ISSUE THREAD

**Issue by TheGr33k** [kmoskwiak/videojs-resolution-switcher#74]
Live demo : https://www.filterbypass.me/livetest.php

https://gyazo.com/55b0069ad2d5398f425c681f74999f6c

Anyone know what i am doing wrong ?

**Comment by Mg-Yaya** [comment]
in **videojs-resolution-switcher.js** line **122** add this : 

`videojs.addClass(staticLabel, 'vjs-icon-cog');`  after  `videojs.addClass(staticLabel, 'vjs-resolution-button-staticlabel');`

**Comment by yatikh** [comment]
I have met recently the same problem. It's just enough to include _videojs-resolution-switcher.css_ file from _lib_ folder of the plugin into your page.

**Comment by kmoskwiak** [comment]
Hi,
as @yatikh said - you have to include videojs-resolution-switcher.css file

**Comment by gimmins** [comment]
Looks like there is some naming mismatch. I had to add the following properties inside `videojs-resolution-switcher.css` 

```
.vjs-resolution-button .vjs-menu-button .vjs-icon-placeholder::before {
  font-family: VideoJS;
  content: '\f110';
  font-size: 1.8em;
  line-height: 1.67;
}
```

also, add `display: none;` to `.vjs-resolution-button .vjs-resolution-button-label` properties, and that should show gear icon (and remove resolution quality text).

**Comment by mzulkiakbari** [comment]
This code for Videojs Version 7+ or 6+

i am fixing.

https://github.com/bariartz/videojs-resolution-switcher-for-videojs-version-7/

sorry for my bad english.
