### ISSUE TITLE
Does not work with iOS (9 or minor?) on iPhone

### ISSUE THREAD

**Issue by thesainthell** [kmoskwiak/videojs-resolution-switcher#8]
Hi,
I've noticed some behavior which I have to say I'm not sure if it is a bug or just the lack of how iOS treats such implementations.
When using your plugin on iOS on the iPhone the native Player shows up and no resolution can be chosen. 

So, any suggestions if it is a bug of the plugin or just because of the native video player of iOS? To be clear, this just happens on iPhone not on iPad.

**Comment by kmoskwiak** [comment]
Does the native video player show up when plugin is not enabled?

**Comment by thesainthell** [comment]
Yes the native player appears also if the plugin isn't loaded.

**Comment by kmoskwiak** [comment]
I think it is video.js issue. Maybe video.js does not support iOS on iPhone.

**Comment by alobimday** [comment]
videojs works on iOS, resolution button is displayed but this can not switch.
