### ISSUE TITLE
Videojs 5.20.3 ?

### ISSUE THREAD

**Issue by surikat1978** [kmoskwiak/videojs-resolution-switcher#97]
Hi!  Don't work with version videojs 5.20.3  
When you can wait for the current plugin?
Thanks Advance!

**Comment by surikat1978** [comment]
Hooray! It works! I forgot to put this into the page:
`<script>
   videojs ('video'). videoJsResolutionSwitcher ()
</ script>`

**Comment by mayeaux** [comment]
Maybe close the issue now that you have it working?

**Comment by surikat1978** [comment]
No problem! close it. Thank you so much!
